[versions]
kotlin = "2.4.0"
intellij-platform-plugin = "2.18.1"

intellij-ide = "2026.2"
intellij-since = "262"
intellij-until = "262.*"

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
intellij-platform = { id = "org.jetbrains.intellij.platform", version.ref = "intellij-platform-plugin" }