[versions]
kotlin = "2.2.0-RC2"

intellij-platform = "2.13.1"
intellij-ide = "2026.1"
intellij-since = "261"
intellij-until = "261.*"

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
intellij-platform = { id = "org.jetbrains.intellij.platform", version.ref = "intellij-platform" }