[versions]
kotlin = "2.1.21"

intellij-platform = "2.6.0"
intellij-ide = "252.23591.19-EAP-SNAPSHOT"
intellij-since = "252"
intellij-until = "252.*"

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
intellij-platform = { id = "org.jetbrains.intellij.platform", version.ref = "intellij-platform" }