[versions]
kotlin = "2.2.0-RC2"

intellij-platform = "2.13.1"
intellij-ide = "262.5752.32-EAP"
intellij-since = "262"
intellij-until = "262.*"

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
intellij-platform = { id = "org.jetbrains.intellij.platform", version.ref = "intellij-platform" }